### ISSUE TITLE
Jenkins handler is not restarting correctly

### ISSUE THREAD

**Issue by maubarrerag** [donovosoft/ansible-scripts#4]
**Simulate error**
`ansible-playbook -i aws-env conf_playbooks/jenkins-infra.yml --diff -vvvv`

**Result**

After jenkins has been installed, the service is not available. Checking the logs we have the following error:

`SEVERE: Container startup failed
java.io.IOException: Failed to start a listener: winstone.Ajp13ConnectorFactory
        at winstone.Launcher.spawnListener(Launcher.java:207)
        at winstone.Launcher.<init>(Launcher.java:148)
        at winstone.Launcher.main(Launcher.java:352)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at Main._main(Main.java:246)
        at Main.main(Main.java:91)
Caused by: java.lang.UnsupportedOperationException: AJP support is removed in Winstone 3.0 due to Jetty 9 not supporting AJP. For reverse proxying, please use HTTP instead of AJP.
        at winstone.Ajp13ConnectorFactory.start(Ajp13ConnectorFactory.java:31)
        at winstone.Launcher.spawnListener(Launcher.java:205)
        ... 8 more
`

**Suggestions**

We should have a template for jenkins configuration this should be fixed changing:
`JENKINS_JAVA_CMD="" `
For something that works. Use the following as example:

`java -jar /usr/lib/jenkins/jenkins.war --ajp13Port=-1 --httpPort=8080`

**Comment by maubarrerag** [comment]
Fixed

**Comment by donovosoft** [comment]
Its ok
